resilience4j:
  circuitbreaker:
    instances:
      movieService:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
spring:
  profiles:
    active:
    - dev				
server:
  port: 9080
			
